### ISSUE TITLE
Rerunning spamostack with the same config.json file gives AttributeError

### ISSUE THREAD

**Issue by corest** [seecloud/spamostack#18]
Steps to reproduce (on devstack environment):
1. Dump all databases
2. Install spamostack in virtual environment
3. Run spamostack with default configuration
4. Restore all databases
5. Run spamostack with default configuration

> 2016-10-12T15:21:07UTC session.py DEBUG: REQ: curl -g -i -X GET http://192.168.122.4/identity/v3/users/71d6349c539048e9abc02c4f116732f1 -H "User-Agent: python-keystoneclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}181921bfefb62f4288622c877e98780030f33230"
> 2016-10-12T15:21:07UTC connectionpool.py DEBUG: "GET /identity/v3/users/71d6349c539048e9abc02c4f116732f1 HTTP/1.1" 404 114
> 2016-10-12T15:21:07UTC session.py DEBUG: RESP: [404] Date: Wed, 12 Oct 2016 15:21:07 GMT Server: Apache/2.4.7 (Ubuntu) Vary: X-Auth-Token x-openstack-request-id: req-332cd35c-f0f1-473d-9e9f-4e95a21947e6 Content-Length: 114 Keep-Alive: timeout=5, max=95 Connection: Keep-Alive Content-Type: application/json 
> RESP BODY: {"error": {"message": "Could not find user: 71d6349c539048e9abc02c4f116732f1", "code": 404, "title": "Not Found"}}
> 
> 2016-10-12T15:21:07UTC session.py DEBUG: Request returned failure status: 404
> Traceback (most recent call last):
>   File "/home/stack/spamvenv/bin/spamostack", line 10, in <module>
>     sys.exit(main())
>   File "/home/stack/spamostack/spamostack/main.py", line 70, in main
>     simulators.append(Simulator(pipe_name, pipe, cache, admin_keeper))
>   File "/home/stack/spamostack/spamostack/simulator.py", line 53, in **init**
>     self.client_factory = ClientFactory(self.cache, self.user, self.keeper)
>   File "/home/stack/spamostack/spamostack/client_factory.py", line 95, in **init**
>     user_copy = self.cache["users"][user.name].copy()
> AttributeError: 'NoneType' object has no attribute 'name'

**Comment by ivanovmi** [comment]
@corest what db did you dumped?

**Comment by corest** [comment]
@ivanovmi all databases
